### ISSUE TITLE
Floats

### ISSUE THREAD

**Issue by timrach** [nicolewhite/algebra.js#20]
I just changed some code to support initializing,adding,subtracting,multiplying and dividing expressions with floats. The only thing i did is a type conversion from float to Fraction, so no evaluation code was touched. Is that something you want or is the restriction to integer numbers for those operations intentional?

Edit: See the code changes here: https://github.com/nicolewhite/algebra.js/compare/master...timrach:decimals?expand=1

**Comment by nicolewhite** [comment]
It was intentional as I wanted to keep everything rational. It will also produce some pretty ugly output, e.g.

```js
var exp = new Expression("x");
exp = exp.multiply(1/3);

exp.toString(); // 0.3333333333333333x
```

If anything, I'd rather the changes be made to Fraction so you could do:

```js
var frac = new Fraction(0.5); // 1/2
```

Although I'm not sure how you'd handle repeating decimals:

```js
var frac = new Fraction(1/3);
```

as your current strategy of multiplying and dividing by 10^length of decimal wouldn't work here.

**Comment by timrach** [comment]
I see, that makes sense. I close this issue then.
